import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  // Extend pages table
  const hasTemplateType = await knex.schema.hasColumn('pages', 'template_type');
  if (!hasTemplateType) {
    await knex.schema.alterTable('pages', (table) => {
      table.string('template_type', 30).nullable();
    });
  }

  const hasAutoGenerated = await knex.schema.hasColumn('pages', 'auto_generated');
  if (!hasAutoGenerated) {
    await knex.schema.alterTable('pages', (table) => {
      table.boolean('auto_generated').notNullable().defaultTo(false);
    });
  }

  // Extend notifications table
  const hasChannel = await knex.schema.hasColumn('notifications', 'channel');
  if (!hasChannel) {
    await knex.schema.alterTable('notifications', (table) => {
      table.string('channel', 20).notNullable().defaultTo('internal');
    });
  }

  const hasExternalSent = await knex.schema.hasColumn('notifications', 'external_sent');
  if (!hasExternalSent) {
    await knex.schema.alterTable('notifications', (table) => {
      table.boolean('external_sent').notNullable().defaultTo(false);
    });
  }

  const hasScheduledAt = await knex.schema.hasColumn('notifications', 'scheduled_at');
  if (!hasScheduledAt) {
    await knex.schema.alterTable('notifications', (table) => {
      table.timestamp('scheduled_at').nullable();
    });
  }
}

export async function down(knex: Knex): Promise<void> {
  // Revert notifications columns
  const hasScheduledAt = await knex.schema.hasColumn('notifications', 'scheduled_at');
  if (hasScheduledAt) {
    await knex.schema.alterTable('notifications', (table) => {
      table.dropColumn('scheduled_at');
    });
  }

  const hasExternalSent = await knex.schema.hasColumn('notifications', 'external_sent');
  if (hasExternalSent) {
    await knex.schema.alterTable('notifications', (table) => {
      table.dropColumn('external_sent');
    });
  }

  const hasChannel = await knex.schema.hasColumn('notifications', 'channel');
  if (hasChannel) {
    await knex.schema.alterTable('notifications', (table) => {
      table.dropColumn('channel');
    });
  }

  // Revert pages columns
  const hasAutoGenerated = await knex.schema.hasColumn('pages', 'auto_generated');
  if (hasAutoGenerated) {
    await knex.schema.alterTable('pages', (table) => {
      table.dropColumn('auto_generated');
    });
  }

  const hasTemplateType = await knex.schema.hasColumn('pages', 'template_type');
  if (hasTemplateType) {
    await knex.schema.alterTable('pages', (table) => {
      table.dropColumn('template_type');
    });
  }
}
